# NOTE: We ignore .js and .cjs files as they are related to cursorless node extensions
# generated outside of that repo and are "binary" files.
# TODO: use exclude at top level, see https://pre-commit.com/#top_level-exclude
minimum_pre_commit_version: "3.2.0"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: .cjs$
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: fix-byte-order-marker
      # NB. To avoid sometimes needing multiple runs, we need:
      # - trailing-whitespace BEFORE end-of-file-fixer,
      #   otherwise trailing newline followed by whitespace, "\n ",
      #   will need multiple runs.
      # - end-of-file-fixer   BEFORE mixed-line-ending,
      #   otherwise a file with CRLF line endings but missing a trailing
      #   newline will need multiple runs.
      - id: trailing-whitespace
        exclude: .js$
      - id: end-of-file-fixer
        exclude: .js$
      - id: mixed-line-ending
        exclude: .js$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        exclude: .js$
  - repo: https://github.com/rwxcorp/pre-commit-lua.git
    rev: v1.0.0
    hooks:
      - id: stylua
      - id: luacheck
